alter table "public"."test" drop constraint "test_pkey";

drop index if exists "public"."test_pkey";

drop table "public"."test";

create table "public"."Investment" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" character varying not null,
    "content" character varying,
    "investment_id" bigint
);


alter table "public"."Investment" enable row level security;

create table "public"."Journey" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" character varying not null
);


alter table "public"."Journey" enable row level security;

CREATE UNIQUE INDEX "Investment_pkey" ON public."Investment" USING btree (id);

CREATE UNIQUE INDEX "Journey_pkey" ON public."Journey" USING btree (id);

alter table "public"."Investment" add constraint "Investment_pkey" PRIMARY KEY using index "Investment_pkey";

alter table "public"."Journey" add constraint "Journey_pkey" PRIMARY KEY using index "Journey_pkey";

alter table "public"."Investment" add constraint "Investment_investment_id_fkey" FOREIGN KEY (investment_id) REFERENCES "Journey"(id) not valid;

alter table "public"."Investment" validate constraint "Investment_investment_id_fkey";


